# Generated by Django 4.2 on 2026-04-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(default='București', max_length=100)),
                ('boundary_geojson', models.JSONField(blank=True, help_text='GeoJSON geometry for the district boundary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('cleanliness', 'Cleanliness'), ('safety', 'Safety'), ('transport', 'Transport'), ('greenspace', 'Green Spaces'), ('other', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Topic categories',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('x', 'X (Twitter)'), ('google_maps', 'Google Maps'), ('facebook', 'Facebook Groups')], max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='Original post ID from the source platform', max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score from -1.0 (negative) to +1.0 (positive)', null=True)),
                ('sentiment_label', models.CharField(blank=True, help_text='Positive, Negative, or Neutral', max_length=20)),
                ('topic_scores', models.JSONField(blank=True, help_text='Dict of topic_name -> confidence score', null=True)),
                ('score', models.IntegerField(default=0, help_text='Upvotes/reactions/rating')),
                ('extra_data', models.JSONField(blank=True, help_text='Additional source-specific data', null=True)),
                ('language', models.CharField(blank=True, default='ro', max_length=10)),
                ('ingestion_method', models.CharField(choices=[('scraper', 'Automated scraper'), ('manual_paste', 'Manual paste (ingestion module)')], default='scraper', max_length=20)),
                ('original_date', models.DateTimeField(blank=True, help_text='Original post creation date from the source', null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analytics.district')),
                ('topics', models.ManyToManyField(blank=True, related_name='posts', to='analytics.topiccategory')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_type', models.CharField(max_length=50)),
                ('intensity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('avg_sentiment', models.FloatField(help_text='Average sentiment score across all posts in this period')),
                ('post_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0, help_text='Number of posts with negative sentiment')),
                ('overall_score', models.FloatField(help_text='Combined district score (0–10 scale)')),
                ('grade', models.CharField(blank=True, help_text='Letter grade A–F', max_length=2)),
                ('topic_breakdown', models.JSONField(blank=True, help_text='Dict of topic_name -> {count, avg_sentiment}', null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='analytics.district')),
            ],
            options={
                'ordering': ['-period_end', 'district'],
            },
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['source', 'source_id'], name='analytics_s_source_2ddb32_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['district'], name='analytics_s_distric_ebecaf_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['sentiment_label'], name='analytics_s_sentime_c76452_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['-scraped_at'], name='analytics_s_scraped_f7ec3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialpost',
            unique_together={('source', 'source_id')},
        ),
        migrations.AlterUniqueTogether(
            name='districtscore',
            unique_together={('district', 'period_start', 'period_end')},
        ),
    ]
