# Generated by Django 4.2 on 2026-04-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['kind', 'name']},
        ),
        migrations.AddField(
            model_name='district',
            name='centroid_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='centroid_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='kind',
            field=models.CharField(choices=[('city', 'City'), ('sector', 'Sector'), ('quarter', 'Quarter')], default='sector', help_text='Hierarchy level — city → sector → quarter.', max_length=10),
        ),
        migrations.AddField(
            model_name='district',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Parent geographic unit (e.g. a quarter's sector).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='analytics.district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon/multipolygon for the district boundary.', null=True),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['kind'], name='analytics_d_kind_9fb896_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['parent'], name='analytics_d_parent__d082fc_idx'),
        ),
    ]
