"""baseline - UrbanPulse schema (data + RAG tables, pgvector)

Represents the existing Supabase schema the FastAPI app owns. On the live
database this revision is applied with ``alembic stamp 0001_baseline`` (the
tables already exist); on a fresh database ``alembic upgrade head`` recreates
everything from scratch.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-06
"""
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


UPGRADE_SQL = r"""
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS analytics_topiccategory (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) UNIQUE NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS analytics_district (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) UNIQUE NOT NULL,
    city             VARCHAR(100) NOT NULL DEFAULT 'București',
    kind             VARCHAR(10)  NOT NULL DEFAULT 'sector',
    parent_id        BIGINT REFERENCES analytics_district(id) ON DELETE SET NULL,
    boundary_geojson JSONB,
    centroid_lat     DOUBLE PRECISION,
    centroid_lng     DOUBLE PRECISION,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS analytics_socialpost (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source           VARCHAR(20)  NOT NULL,
    source_id        VARCHAR(255) NOT NULL DEFAULT '',
    content          TEXT NOT NULL,
    author           VARCHAR(255) NOT NULL DEFAULT '',
    url              VARCHAR(200) NOT NULL DEFAULT '',
    latitude         DOUBLE PRECISION,
    longitude        DOUBLE PRECISION,
    location_name    VARCHAR(255) NOT NULL DEFAULT '',
    district_id      BIGINT REFERENCES analytics_district(id) ON DELETE SET NULL,
    sentiment_score  DOUBLE PRECISION,
    sentiment_label  VARCHAR(20) NOT NULL DEFAULT '',
    topic_scores     JSONB,
    score            INTEGER NOT NULL DEFAULT 0,
    extra_data       JSONB,
    language         VARCHAR(10) NOT NULL DEFAULT 'ro',
    ingestion_method VARCHAR(20) NOT NULL DEFAULT 'scraper',
    original_date    TIMESTAMPTZ,
    scraped_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at     TIMESTAMPTZ,
    CONSTRAINT analytics_socialpost_source_source_id_uniq UNIQUE (source, source_id)
);
CREATE INDEX IF NOT EXISTS analytics_s_sentime_idx ON analytics_socialpost (sentiment_label);
CREATE INDEX IF NOT EXISTS analytics_s_scraped_idx ON analytics_socialpost (scraped_at DESC);
CREATE INDEX IF NOT EXISTS analytics_socialpost_district_id_idx ON analytics_socialpost (district_id);

CREATE TABLE IF NOT EXISTS analytics_socialpost_topics (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    socialpost_id    BIGINT NOT NULL REFERENCES analytics_socialpost(id) ON DELETE CASCADE,
    topiccategory_id BIGINT NOT NULL REFERENCES analytics_topiccategory(id) ON DELETE CASCADE,
    CONSTRAINT analytics_socialpost_topics_uniq UNIQUE (socialpost_id, topiccategory_id)
);

CREATE TABLE IF NOT EXISTS analytics_districtscore (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id   BIGINT NOT NULL REFERENCES analytics_district(id) ON DELETE CASCADE,
    period_start  TIMESTAMPTZ NOT NULL,
    period_end    TIMESTAMPTZ NOT NULL,
    avg_sentiment DOUBLE PRECISION NOT NULL,
    post_count    INTEGER NOT NULL DEFAULT 0,
    issue_count   INTEGER NOT NULL DEFAULT 0,
    overall_score DOUBLE PRECISION NOT NULL,
    grade         VARCHAR(2) NOT NULL DEFAULT '',
    topic_breakdown JSONB,
    computed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rag_postembedding (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT UNIQUE NOT NULL REFERENCES analytics_socialpost(id) ON DELETE CASCADE,
    embedding  vector(768),
    model_name VARCHAR(100) NOT NULL DEFAULT 'nomic-embed-text',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS rag_postembedding_embedding_hnsw
    ON rag_postembedding USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE TABLE IF NOT EXISTS rag_feedback (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         VARCHAR(64) NOT NULL DEFAULT '',
    question           TEXT NOT NULL,
    answer             TEXT NOT NULL,
    retrieved_post_ids JSONB NOT NULL DEFAULT '[]',
    rating             VARCHAR(10) NOT NULL,
    context_score      DOUBLE PRECISION,
    answer_score       DOUBLE PRECISION,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS rag_feedbac_rating_idx  ON rag_feedback (rating);
CREATE INDEX IF NOT EXISTS rag_feedbac_session_idx ON rag_feedback (session_id);
"""

DOWNGRADE_SQL = r"""
DROP TABLE IF EXISTS rag_feedback CASCADE;
DROP TABLE IF EXISTS rag_postembedding CASCADE;
DROP TABLE IF EXISTS analytics_districtscore CASCADE;
DROP TABLE IF EXISTS analytics_socialpost_topics CASCADE;
DROP TABLE IF EXISTS analytics_socialpost CASCADE;
DROP TABLE IF EXISTS analytics_district CASCADE;
DROP TABLE IF EXISTS analytics_topiccategory CASCADE;
"""


def upgrade():
    op.execute(UPGRADE_SQL)


def downgrade():
    op.execute(DOWNGRADE_SQL)
