"""Alembic environment.

Pulls the DB URL and target metadata from the FastAPI app so there's a single
source of truth. ``include_object`` restricts autogenerate to the tables the app
owns, so Alembic never proposes dropping the Supabase SQL views (feedbacks,
quarters_map, …) or any table outside our models.
"""

from logging.config import fileConfig

from alembic import context

from app.config import DATABASE_URL
from app.db import Base, engine
import app.models  # noqa: F401 - register models on Base.metadata

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)
# NB: we deliberately do NOT write DATABASE_URL into the alembic config via
# set_main_option - the URL-encoded password contains '%' which ConfigParser
# would try to interpolate. We use app.db.engine / DATABASE_URL directly instead.

target_metadata = Base.metadata

# Only these tables are managed by Alembic; everything else in the DB is ignored.
MANAGED_TABLES = set(target_metadata.tables.keys())


def include_object(obj, name, type_, reflected, compare_to):
    """Restrict Alembic to the app's own tables (and their columns).

    Incidental indexes / FKs / unique constraints created in raw SQL (e.g. the
    HNSW vector index, the Django-era index names) are intentionally NOT managed
    by autogenerate, so an accidental `alembic revision --autogenerate` can never
    propose dropping them. The SQLAlchemy models are a pragmatic mirror of the
    schema for the ORM; deliberate schema changes should be written by hand as
    new revisions, not blindly autogenerated.
    """
    if type_ == "table":
        return name in MANAGED_TABLES
    if type_ in ("index", "unique_constraint", "foreign_key_constraint"):
        return False
    return True


def run_migrations_offline():
    context.configure(
        url=DATABASE_URL, target_metadata=target_metadata,
        literal_binds=True, include_object=include_object, compare_type=False,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online():
    with engine.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata,
            include_object=include_object, compare_type=False,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
